version: '2.1'

services:

  samba:
     image: dperson/samba:rpi
     restart: always
     command: '-u "pi;o928oH@YH" -s "musica;/media/pi/datos/Musica;yes;no" -s "javier;/media/pi/datos/Javier;yes;no"'
     stdin_open: true
     tty: true
     ports:
       - 139:130
       - 445:445
     volumes:
       - /usr/share/zoneinfo/Europe/Madrid:/etc/locatime
       - /media/pi/datos:/media/pi/datos

  plex: 
     image: jaymoulin/plex:latest
     expose:
       - 32400
       - 33400
     hostname: javimetal
     volumes:
       - /media/pi/datos/Plex Media Server:/root/Library/Application Support/Plex Media Server
       - /media/pi/datos:/media
       - /media/pi/datos/tmp:/tmp
     restart: unless-stopped
     networks:
       lan:
         ipv4_address: 192.168.1.3

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - /media/pi/datos/qbittorrent/config:/config
      - /media/pi/datos/qbittorrent/download:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 3080:8080
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /media/pi/datos/jackett/config:/config
      - /media/pi/datos/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 8384:8384
      - 22000:2200
      - 21027:21027/udp
    volumes:
      - /media/pi/datos/syncthing/config:/config
      - /media/pi/datos/Javier:/javier
      - /media/pi/datos/Sonsoles:/sonsoles
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=javimetal
      - TOKEN=7026fdd7-2f52-45c6-bffa-fbb87d3650f4
      - LOG_FILE=false
    volumes:
      - /media/pi/datos/duckdns/config:/config
    restart: unless-stopped
    
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=javimetal.duckdns.org
      - SUBDOMAINS=www,
      - VALIDATION=duckdns
      - DNSPLUGIN=cloudfare #optional
      - DUCKDNSTOKEN=7026fdd7-2f52-45c6-bffa-fbb87d3650f4
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
    volumes:
      - /media/pi/datos/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 1080:80/tcp
      - 1443:443/tcp
    environment:
      TZ: Europe/Madrid
    volumes:
      - /media/pi/datos/pihole/etc-pihole/:/etc/pihole/
      - /media/pi/datos/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
 lan:
   driver: macvlan
   driver_opts:
     parent: eth0
   ipam:
     config:
       - subnet: "192.168.1.0/24"
         gateway: "192.168.1.1"
