version: '2.1'

services:

  samba:
     image: dperson/samba:rpi
     container_name: samba
     restart: always
     command: '-u "pi;o928oH@YH" -s "musica;/media/pi/datos/Musica;yes;no" -s "javier;/media/pi/datos/Javier;yes;no" -s "sonsoles;/media/pi/datos/Sonsoles;yes;no"'
     stdin_open: true
     tty: true
     ports:
       - 139:130
       - 445:445
     volumes:
       - /usr/share/zoneinfo/Europe/Madrid:/etc/locatime
       - /media/pi/datos:/media/pi/datos

  plex: 
     image: ghcr.io/linuxserver/plex:1.21.0.3616-d87012962-ls5
     container_name: plex
     network_mode: host
     environment:
       - PUID=1000
       - PGID=1000
       - VERSION=docker
       - PLEX_CLAIM=claim-NsUfhJBtTtofZfW-Ua8N
     volumes:
       - /media/pi/datos/docker/Plex Media Server:/root/Library/Application Support/Plex Media Server
       - /media/pi/datos/Peliculas:/films
       - /media/pi/datos/Series:/tv
       - /media/pi/datos/docker/tmp:/tmp
     restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - /media/pi/datos/docker/qbittorrent/config:/config
      - /media/pi/datos/qbittorrent/download:/downloads
      - /media/pi/datos/Musica:/music
      - /media/pi/datos/Peliculas:/films
      - /media/pi/datos/Series:/tv
    ports:
      - 6881:681
      - 6881:6881/udp
      - 3080:8080
    restart: unless-stopped

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 8384:8384
      - 22000:2200
      - 21027:21027/udp
    volumes:
      - /media/pi/datos/docker/syncthing/config:/config
      - /media/pi/datos/Javier:/javier
      - /media/pi/datos/Sonsoles:/sonsoles
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=javimetal
      - TOKEN=7026fdd7-2f52-45c6-bffa-fbb87d3650f4
      - LOG_FILE=false
    volumes:
      - /media/pi/datos/docker/duckdns/config:/config
    restart: unless-stopped
    
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=javimetal.duckdns.org
      - SUBDOMAINS=www,
      - VALIDATION=duckdns
      - DNSPLUGIN=cloudfare #optional
      - DUCKDNSTOKEN=7026fdd7-2f52-45c6-bffa-fbb87d3650f4
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
    volumes:
      - /media/pi/datos/docker/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 1080:80/tcp
      - 1443:443/tcp
    environment:
      TZ: Europe/Madrid
    volumes:
      - /media/pi/datos/docker/pihole/etc-pihole/:/etc/pihole/
      - /media/pi/datos/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  portainer:
     image: portainer/portainer
     container_name: portainer
     ports:
      - 9000:9000
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     restart: always
