version: '2.1'

services:

  samba:
     image: dperson/samba:rpi
     restart: always
     command: '-u "pi;o928oH@YH" -s "musica;/media/pi/datos/Musica;yes;no" -s "javier;/media/pi/datos/Javier;yes;no"'
     stdin_open: true
     tty: true
     ports:
       - 139:130
       - 445:445
     volumes:
       - /usr/share/zoneinfo/Europe/Madrid:/etc/locatime
       - /media/pi/datos:/media/pi/datos

  plex: 
     image: jaymoulin/plex
     expose:
       - 32400
       - 33400
     hostname: javimetal
     volumes:
       - /media/pi/datos/Plex Media Server:/root/Library/Application Support/Plex Media Server
       - /media/pi/datos:/media
       - /media/pi/datos/tmp:/tmp
     restart: unless-stopped
     networks:
       lan:
         ipv4_address: 192.168.1.3

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - /media/pi/datos/qtorrent/config:/config
      - /media/pi/datos/qtorrent/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

networks:
 lan:
   driver: macvlan
   driver_opts:
     parent: eth0
   ipam:
     config:
       - subnet: "192.168.1.0/24"
         gateway: "192.168.1.1"
