version: '2'

services:

  samba:
     image: dperson/samba:rpi
     restart: always
     command: '-u "pi;o928oH@YH" -s "musica;/media/pi/datos/Musica;yes;no" -s "javier;/media/pi/datos/Javier;yes;no"'
     stdin_open: true
     tty: true
     ports:
       - 139:130
       - 445:445
     volumes:
       - /usr/share/zoneinfo/Europe/Madrid:/etc/locatime
       - /media/pi/datos:/media/pi/datos

  transmission:
     image: ghcr.io/linuxserver/transmission
     command: transmission-daemon -f -g /config
     volumes:
       - /media/pi/datos/transmission/config:/config
       - /media/pi/datos/transmission/downloads:/downloads
     ports:
       - 9091:9091
       - 51413:52413
       - 51413:52413/udp
     expose:
       - 9191
     restart: always

  plex: 
     image: jaymoulin/plex
     expose:
       - 32400
       - 33400
     hostname: javimetal
     volumes:
       - /media/pi/datos/Plex Media Server:/root/Library/Application Support/Plex Media Server
       - /media/pi/datos:/media
       - /media/pi/datos/tmp:/tmp
     restart: unless-stopped
     networks:
       lan:
         ipv4_address: 192.168.1.3

networks:
 lan:
   driver: macvlan
   driver_opts:
     parent: eth0
   ipam:
     config:
       - subnet: "192.168.1.0/24"
         gateway: "192.168.1.1"
