version: '2.1'

services:

  samba:
     image: dperson/samba:rpi
     container_name: samba
     restart: always
     command: '-u "pi;o928oH@YH" -s "media;/media;yes;no" -s "downloads;/downloads/yes;no"'
     stdin_open: true
     tty: true
     ports:
       - 139:130
       - 445:445
     volumes:
       - /usr/share/zoneinfo/Europe/Madrid:/etc/locatime
       - /media/pi/datos:/media
       - /media/pi/datos/qbittorrent/download:/downloads

  plex: 
     image: ghcr.io/linuxserver/plex:arm32v7-latest
     container_name: plex
     network_mode: host
     environment:
       - PUID=1000
       - PGID=1000
       - VERSION=docker
       - PLEX_CLAIM=claim-NsUfhJBtTtofZfW-Ua8N
     volumes:
       - /media/pi/datos/docker/plex/config:/config
       - /media/pi/datos/Peliculas:/films
       - /media/pi/datos/Series:/tv
       - /media/pi/datos/Kids:/kids
       - /media/pi/datos/Kids_Series:/kids_tv
       - /media/pi/datos/docker/plex/tmp:/tmp
     restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/javier/docker/qbittorrent/appdata:/config
      - /home/javier/media/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 8384:8384
      - 22000:2200
      - 21027:21027/udp
    volumes:
      - /media/pi/datos/docker/syncthing/config:/config
      - /media/pi/datos/Javier:/javier
      - /media/pi/datos/Sonsoles:/sonsoles
    restart: unless-stopped

  portainer:
     image: portainer/portainer:latest
     container_name: portainer
     ports:
      - 9000:9000
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     restart: always

  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=wireguard.jaestsantech.org #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /home/javier/docker/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - /home/javier/docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 15m
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/home/javier/docker/navidrome:/data"
      - "/home/javier/media/musica:/music:rw"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/javier/docker/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/javier/docker/lidarr/config:/config
      - /home/javier/media/musica:/music
      - /home/javier/media/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
     - /home/javier/docker/calibre/config:/config
     - /home/javier/docker/calibre/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped

    watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true 
      - WATCHTOWER_INCLUDE_RESTARTING=true 
      - WATCHTOWER_INCLUDE_STOPPED=true 
      - WATCHTOWER_REVIVE_STOPPED=false 
      - WATCHTOWER_NO_RESTART=false 
      - WATCHTOWER_TIMEOUT=30s 
      - WATCHTOWER_SCHEDULE=0 0 7 * * * 
      - WATCHTOWER_DEBUG=false
    restart: always
