version: '3'

services:
   chrome:
        image: selenium/node-chrome
        volumes:
           - /dev/shm:/dev/shm
        depends_on:
           - selenium-hub
        environment:
           - HUB_PORT_4444_TCP_ADDR=selenium-hub
           - HUB_PORT_4444_TCP_PORT=4444
           - NODE_MAX_INSTANCES=3
        ports:
           - 6900:5900
        restart: unless-stopped

   firefox:
        image: selenium/node-firefox
        volumes:
           - /dev/shm:/dev/shm
        depends_on:
           - selenium-hub
        environment:
           - HUB_PORT_4444_TCP_ADDR=selenium-hub
           - HUB_PORT_4444_TCP_PORT=4444
           - NODE_MAX_INSTANCES=3
        ports:
           - 6902:5900
        restart: unless-stopped

   selenium-hub:
        image: selenium/hub
        container_name: selenium-hub
        ports:
           - 4444:4444
        restart: unless-stopped
