version: "2.1"

services:

  syncthing:
     image: linuxserver/syncthing
     container_name: syncthing
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Europe/Madrid
     ports:
       - 8384:8384
       - 22000:2200
       - 21027:21027/udp
     volumes:
       - /media/pi/datos/syncthing/config:/config
       - /media/pi/datos/Javier:/javier
       - /media/pi/datos/Sonsoles:/sonsoles
     restart: unless-stopped
