version: "2.1"

services:

  wireguard:
     image: linuxserver/wireguard
     container_name: wireguard
     cap_add:
       - NET_ADMIN
       - SYS_MODULE
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Europe/Madrid
       - SERVERURL=javimetal.ddns.net
       - SERVERPORT=51820
       - PEERS=2
       - PEERDNS=auto
       - INTERNAL_SUBNET=10.13.13.0
     ports:
       - 51820:51820/udp
     volumes:
       - /media/pi/datos/wireguard/config:/config
       - /lib/modules:/lib/modules
     sysctls:
       - net.ipv4.conf.all.src_valid_mark=1
     restart: always
